spring.application.name=vektor-api

spring.security.user.name=elinor

spring.datasource.url=jdbc:postgresql://localhost:5432/vektordb
spring.datasource.username=vektoruser
spring.datasource.password=vektorpassword
